10 delete comment
tuttitaken01/Portfolio-Project pull request #10
Opened 2023-01-19 16:20 UTC by tuttitaken01

task 10 done
edited task 8 based on feedback
task 9 had already done (comment count added to /api/reviews/:review_id endpoint)

2023-01-19 16:31 UTC, Hard-Luck requested changes
Just need some more tests and a refactor

2023-01-19 16:31 UTC, Hard-Luck commented on __tests__/app.test.js
> +    describe("DELETE /api/comments/commId", () => {
need test for a ID that doesnt exist and an id of the wrong type

2023-01-19 16:31 UTC, Hard-Luck commented on controllers/controllers.js
> +    const id = req.params["commId"];
This should be extracted to the model, the controller should handle the request response and the model should handle all the data queries and formatting

2023-01-20 11:32 UTC, two-triangles commented
Hey Valentina, you haven't addressed Mark's comment regarding making your model dealing with interactions to the database. 

Please remove any console.logs that need to be removed.

2023-01-20 14:27 UTC, merged